### ISSUE TITLE
application key cannot be saved

### ISSUE THREAD

**Issue by magwas** [edemo/wp_oauth_plugin#78]
on the configuration page

**Comment by Claymanus** [comment]
Valami info jól jönne arról, hogy milyen körülmények között futottál bele ebbe

**Comment by magwas** [comment]
end-to-end test now demonstrates the bug. commit 56a644ab17d8bc16dd50e16fd582062b1a7152ae in magwas repo, develop branch.

# 

## FAIL: test_install_page (InstallTest.InstalltestTest)

Traceback (most recent call last):
  File "/wp_oauth_plugin/end2endtest/InstallTest.py", line 23, in test_install_page
    self.assertFieldValue("EdemoSSO_appkey", "f7354fa2-811f-48b6-9be9-359c5d99d6a4")
  File "/wp_oauth_plugin/end2endtest/InstallTest.py", line 15, in assertFieldValue
    self.assertEqual(value,element.get_property('value'))
AssertionError: 'f7354fa2-811f-48b6-9be9-359c5d99d6a4' != ''
- f7354fa2-811f-48b6-9be9-359c5d99d6a4
-

**Comment by Claymanus** [comment]
fixed in 229c56146cbe21b8cef5dbbeae4561dd74659db4
